"""Renamed id to recording_id

Revision ID: 52b2c8673ef3
Revises: 6bd7320f8a66
Create Date: 2024-11-17 19:56:15.947193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52b2c8673ef3'
down_revision: Union[str, None] = '6bd7320f8a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'id', new_column_name='recording_id')


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'recording_id', new_column_name='id')
# ### end Alembic commands ###
