"""Made sensor_id nullable in measurement table

Revision ID: 6bd7320f8a66
Revises: 0d3c94bb8606
Create Date: 2024-11-14 23:32:53.592528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bd7320f8a66'
down_revision: Union[str, None] = '0d3c94bb8606'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'sensor_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
