"""test

Revision ID: 1717de7da888
Revises: a30ae48eb05a
Create Date: 2024-11-21 14:26:41.215397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1717de7da888'
down_revision: Union[str, None] = 'a30ae48eb05a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measurement', sa.Column('test', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measurement', 'test')
    # ### end Alembic commands ###
