"""Renamed recording_id to id and deleted unit

Revision ID: ddf87eac2ce3
Revises: 52b2c8673ef3
Create Date: 2024-11-21 12:15:46.594223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf87eac2ce3'
down_revision: Union[str, None] = '52b2c8673ef3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'recording_id', new_column_name='id')
    op.drop_column('measurement', 'unit')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('measurement', 'id', new_column_name='recording_id')
    op.add_column('measurement', sa.Column('unit', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
